### PR TITLE
Memory allocation optimization

### PR DESCRIPTION
**Pull request by Yves57**
First pass to optimize memory management.
Autobahn tests OK.

- Refactoring code to send frames in one unique method.
- Removing array allocation in `Utilities.MaskInPlane()`.
- Removing FrameHeader allocation (see #77).
- Removing calls to `GetNextMask()` if not necessary.

Pending:
- Still FrameHeader allocation on frame receive.
- Clean the FrameHeader code.

### CODE REVIEW

**Comment by Tratcher** [comment]
Ambitious.  FYI: We're trying to merge this implementation with the one in corefx, so we'll postpone most perf work until that gets worked out.

**Comment by anurse** [comment]
Yeah, we're actively working to remove this and replace it with the implementation in corefx. I know performance will be a concern for them, but I don't know the specifics.

For reference, the implementation we're looking at is this: https://github.com/dotnet/corefx/tree/master/src/System.Net.WebSockets.Client . It's nominally a "client" infrastructure but since send/receive semantics are the same on either send we're hoping to get something common that we can use out of that.

**Comment by Yves57** [comment]
I agree that it is strange to have two implementations of the same functionnality. What's the best to clean ASP.NET repository? Do I close the PR and delete my branch?

**Comment by Tratcher** [comment]
Yes, we'll close this PR for now. You can hold onto your branch until you see what changes we make.

**Pull request closed without merging**
