### PR TITLE
Syncs up our Websockets with corefx and fixes logging.

### PR DESCRIPTION
**Pull request by jkotalik**
Fix for #198 and syncing

### CODE REVIEW

**Comment by Tratcher** [comment]
Were any tests checking exception messages?

**Comment by anurse** [comment]
Having to manually write the SR.cs file feels bad. @stephentoub I'm kinda assuming there's a process to generate them from RESX files in dotnet/corefx. Is that the case? Would we be able to run that code in our build or is it too deeply intertwined with the rest of the build system.

**Comment by jkotalik** [comment]
@Tratcher These files were directly copied from coreFx. The SR.Format messages were never tested and only used to not throw errors from the coreFx code.

**Comment by jkotalik** [comment]
And yeah, this solution feels ugly. It's either this or we copy SR.cs from CoreFx too and everything needed for log messages.

**Comment by Tratcher** [comment]
This is why we hadn't fixed it yet. Plan B, provide the strings in our own resx and shim it however we need to?

**Comment by anurse** [comment]
Well, the resx coming from CoreFx is good. The problem is the `SR` class that the `ManagedWebSocket` class uses to read them. We could use our own resx code generator to build a separate class for reading the resources and see if it would fit into place as a replacement for `SR` (it might fit without adapting, but if not we can make `SR` an adaptor).

**Comment by anurse** [comment]
> or we copy SR.cs from CoreFx too

As far as I can tell, that's not even an option. The file seems to be generated by a tool during build, it's not checked in: https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=net_Websockets_AlreadyOneOutstandingOperation&type=

**Comment by jkotalik** [comment]
We are going to stop copying from corefx directly.

**Pull request closed without merging**
