### PR TITLE
Tell users what to do with "AccessDenied" exceptions

### PR DESCRIPTION
**Pull request by avanderhoorn**
As per - http://stackoverflow.com/questions/1987749/why-do-i-get-accessdenied-when-trying-to-use-httplistener

### CODE REVIEW

**Comment by avanderhoorn** [comment]
Not sure this build error has to do with me... seems to be a psake problem?

**Comment by Tratcher** [comment]
Or just change it to `http://localhost:12345/`, that doesn't require an acl.

**Comment by avanderhoorn** [comment]
I'm happy with either approach, what would you prefer?

**Comment by Tratcher** [comment]
localhost

**Pull request closed without merging**
